import logging
from langchain.prompts import PromptTemplate
from langchain.chains.llm import LLMChain
from ai_tools.model_selector import get_llm

# Configure logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

def analyze_website_data(metadata: dict) -> str:
    """
    Analyze personal website metadata and generate a summary of the candidate's personal branding.
    
    Parameters:
        metadata (dict): A dictionary containing keys "title", "description" and "keywords".
    
    Returns:
        str: A summary generated by the LLM.
    """
    # Extract data or set default values
    title = metadata.get("title", "No Title")
    desc = metadata.get("description", "No Description")
    keywords = metadata.get("keywords", "No Keywords")
    
    logger.info("Analyzing website data: Title=%s, Description=%s, Keywords=%s", title, desc, keywords)
    
    llm = get_llm()
    prompt_text = (
        "Based on the following website metadata, summarize what it reveals about the candidate's personal branding and focus:\n\n"
        "Title: {title}\n"
        "Description: {desc}\n"
        "Keywords: {keywords}\n\n"
        "Summary:"
    )
    prompt = PromptTemplate(
        input_variables=["title", "desc", "keywords"],
        template=prompt_text
    )
    chain = LLMChain(llm=llm, prompt=prompt)
    try:
        summary = chain.run({
            "title": title,
            "desc": desc,
            "keywords": keywords
        })
        logger.info("Website summary generated: %s", summary)
    except Exception as e:
        summary = f"Error generating website summary: {str(e)}"
        logger.error("Error generating website summary: %s", e)
    return summary

if __name__ == "__main__":
    # Test analyze_website_data
    sample_metadata = {
        "title": "John Doe Portfolio",
        "description": "A personal website showcasing projects in AI and web development.",
        "keywords": "AI, Python, Flask"
    }
    website_summary = analyze_website_data(sample_metadata)
    print("Website Analysis:\n", website_summary)
    